name: shared
description: The shared dart code for the frontend and backend projects
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.10.7
  json_serializable: ^4.0.0
